BookStore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using BookStore.Models;
using BookStore.Services;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace BookStore.Controllers
{
    public class BooksController : Controller
    {

        private AppDbContext _context;
        private UserManager<User> _userManager;
        private CategoriesService categoriesService;

        public BooksController(UserManager<User> userManager)
        {

            var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
            optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=BookStoreDB;Trusted_Connection=True;MultipleActiveResultSets=true");
            this._context = new AppDbContext(optionsBuilder.Options);
            categoriesService = new CategoriesService();
            _userManager = userManager;
        }


        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult AddBook()
        {
            AddBookViewModel model = new AddBookViewModel {
                Categories = new SelectList(_context.Categories.ToList(), "Id", "Name")
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public IActionResult AddBook(AddBookViewModel model)
        {
            if(ModelState.IsValid)
            {
                var newBook = new Book
                {
                    Title = HttpUtility.HtmlEncode(model.Title),
                    Description = HttpUtility.HtmlEncode(model.Description),
                    QuantityAvailable = model.Quantity,
                    Author = model.Author,
                    Price = model.Price,
                    Category = _context.Categories.Single(x => x.Id == model.Category)
                };

                try
                {
                    var addBook = _context.Books.Add(newBook);
                    _context.SaveChanges();
                    ViewBag.Message = "Book created successfully.";
                    model.Categories = new SelectList(_context.Categories.ToList(), "Id", "Name");
                    //return View(model);
                    return RedirectToAction("AddBook");
                }
                catch(Exception ex)
                {
                    //Refactor to display proper message
                    ViewBag.Message = ex.Message;
                    return View(model);
                }

            }

            return View();
        }
		
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new BookCustomer
            {
                Book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id),
                User = await _userManager.GetUserAsync(HttpContext.User)
            };

            if (model.Book == null)
            {
                return NotFound();
            }

            return View(model);
        }

        public async Task<IActionResult> Index(string category, string searchString, int? pageNumber)
        {
            //Get all books and categories from the database
            var categories = await _context.Categories.ToListAsync();
            var books = from book in _context.Books select book;

            //Storing the filters in viewdata object
            ViewData["CategoryFilter"] = !String.IsNullOrEmpty(category) ? category : "All";
            ViewData["CurrentFilter"] = searchString;


            //Get the books only from the requested category.
            if (!String.IsNullOrEmpty(category) && category != "All")
            {
                books = books.Where(b => b.Category.Name == category);
            }

            //Search the title for the given search string
            if (!String.IsNullOrEmpty(searchString)){
                books = books.Where(b => b.Title.Contains(searchString));
            }

            //Create the model for the view
            Tuple<IEnumerable<Category>, PaginatedList<Book>> model = new Tuple<IEnumerable<Category>, PaginatedList<Book>>(categories, await PaginatedList<Book>.CreateAsync(books.AsNoTracking().Include(b => b.Category), pageNumber ?? 1, 10));

            return View(model);
        }

        public async Task<IActionResult> ReadReviews(int? id)
        {
            var reviews = await _context.Review.Where(review => review.BookID == id).Include(review => review.book).Where(review => review.book.Id == id).ToListAsync();
            if (reviews.Count == null || reviews.Count == 0)
            {
                return NotFound();
            } else
            {
                return View(reviews);
            }
        }

        [HttpGet]
        public IActionResult AddReview(int id)
        {
            AddReviewModel model = new AddReviewModel
            {
                BookID = id
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddReview(AddReviewModel model)
        {
            if (ModelState.IsValid)
            {
                var newReview = new Review
                {
                    BookID = _context.Books.Single(x => x.Id == model.BookID).Id,
                    Rating = model.Rating,
                    CustomerReview = model.CustomerReview,
                    ReviewDate = DateTime.Now
                };

                try
                {
                    var addReview = _context.Review.Add(newReview);
                    _context.SaveChanges();
                    ViewBag.Message = "Review created successfully.";
                    //model.BookID = _context.Books.First().Id;
                    return RedirectToAction("ReadReviews", new { id = newReview.BookID });
                }
                catch (Exception ex)
                {
                    //Refactor to display proper message
                    ViewBag.Message = ex.Message;
                    return RedirectToAction("Index");
                }

            }

            return View();
        }
    }
}

BookStore/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{

    
    [Authorize(Roles = "Administrator")]
    public class CategoriesController : Controller
    {
        private AppDbContext _context;

        public CategoriesController() {
            var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
            optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=BookStoreDB;Trusted_Connection=True;MultipleActiveResultSets=true");
            this._context = new AppDbContext(optionsBuilder.Options);
        }


        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }
        
        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddCategoryViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                var newCategory = new Category
                {
                    Name = model.Name
                };
                _context.Categories.Add(newCategory);
                _context.SaveChanges();
                ViewBag.Message = "Category created!";
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Categories/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private AppDbContext _context;
        private UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }



        // GET: Users
        public async Task<ActionResult> Index()
        {
            var users_list = await _userManager.GetUsersInRoleAsync("Administrator");
            return View(users_list);
        }

        // GET: Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.Message = "User was not found";
            }
                return View(user);
        }

            // GET: Users/Create
            public ActionResult Create()
            {
                return View();
            }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Users/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BookStore</a>
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Books" asp-action="Index">Books</a></li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-area="" asp-controller="Categories" asp-action="Create">Categories</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="Books" asp-action="AddBook">Add Book</a></li>
                        
                    }
                </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><p class="text-info">Logged in as: @User.Identity.Name</p></li>
                        <li class="pull-right"><a asp-area="" asp-controller="Account" asp-action="Logout">Log out</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    </ul>
                }

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - BookStore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>